package com.luanvm.coffee.domain;
// default package
// Generated Sep 9, 2013 12:56:17 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThkLanguage generated by hbm2java
 */
@Entity
@Table(name = "thk_language", catalog = "thkassociates")
public class Language implements java.io.Serializable {

	private Integer languageid;
	private String languagename;
	private String languagecode;

	public Language() {
	}

	public Language(String languagename, String languagecode) {
		this.languagename = languagename;
		this.languagecode = languagecode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "languageid", unique = true, nullable = false)
	public Integer getLanguageid() {
		return this.languageid;
	}

	public void setLanguageid(Integer languageid) {
		this.languageid = languageid;
	}

	@Column(name = "languagename", length = 512)
	public String getLanguagename() {
		return this.languagename;
	}

	public void setLanguagename(String languagename) {
		this.languagename = languagename;
	}

	@Column(name = "languagecode", length = 20)
	public String getLanguagecode() {
		return this.languagecode;
	}

	public void setLanguagecode(String languagecode) {
		this.languagecode = languagecode;
	}

}
