package com.luanvm.coffee.domain;
// default package
// Generated Sep 9, 2013 12:56:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThkLog generated by hbm2java
 */
@Entity
@Table(name = "thk_log", catalog = "thkassociates")
public class Log implements java.io.Serializable {

	private Integer logid;
	private int userid;
	private Date modified;
	private String oldcontent;
	private String ip;
	private String metadata;

	public Log() {
	}

	public Log(int userid, Date modified, String oldcontent) {
		this.userid = userid;
		this.modified = modified;
		this.oldcontent = oldcontent;
	}

	public Log(int userid, Date modified, String oldcontent, String ip,
			String metadata) {
		this.userid = userid;
		this.modified = modified;
		this.oldcontent = oldcontent;
		this.ip = ip;
		this.metadata = metadata;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "logid", unique = true, nullable = false)
	public Integer getLogid() {
		return this.logid;
	}

	public void setLogid(Integer logid) {
		this.logid = logid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", nullable = false, length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "oldcontent", nullable = false, length = 65535)
	public String getOldcontent() {
		return this.oldcontent;
	}

	public void setOldcontent(String oldcontent) {
		this.oldcontent = oldcontent;
	}

	@Column(name = "ip", length = 30)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "metadata", length = 65535)
	public String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

}
