package com.luanvm.coffee.domain;
// default package
// Generated Sep 9, 2013 12:56:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThkStory generated by hbm2java
 */
@Entity
@Table(name = "thk_story", catalog = "thkassociates")
public class Story implements java.io.Serializable {

	private Integer storyid;
	private String description;
	private String url;
	private Date created;
	private Integer createdby;
	private Date updated;
	private Integer updatedby;

	public Story() {
	}

	public Story(String description, String url, Date created,
			Integer createdby, Date updated, Integer updatedby) {
		this.description = description;
		this.url = url;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "storyid", unique = true, nullable = false)
	public Integer getStoryid() {
		return this.storyid;
	}

	public void setStoryid(Integer storyid) {
		this.storyid = storyid;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url", length = 512)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 0)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

}
